name: Build Bob Application (Linux)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  APP_NAME: "Bob"
  BUILD_NUMBER: 1
  BUILD_VERSION: "1.0.0"
  PYTHON_VERSION: "3.10.15"
  FLET_VERSION: "0.27.6" # Renamed for clarity, refers to flet package version
  PYTHONUTF8: 1

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends ninja-build libgtk-3-dev patchelf
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Install Python dependencies
        working-directory: ./src
        run: |
          python -m pip install --upgrade pip
          pip install flet==${{ env.FLET_VERSION }}
          # Install CPU-only PyTorch first with explicit index URL
          pip install torch --index-url https://download.pytorch.org/whl/cpu --no-cache-dir
          # Install other requirements from src/requirements.txt
          pip install -r requirements.txt --no-cache-dir
          # Verify installation
          python -c "import torch; print(f'PyTorch version: {torch.__version__}, CUDA: {torch.cuda.is_available()}')"
          pip cache purge

      - name: Build application
        working-directory: ./src
        run: |
          rm -rf build/
          flet build linux \
          --project-name "${{ env.APP_NAME }}" \
          --description "Bob The Lawyer Application" \
          --build-number ${{ env.BUILD_NUMBER }} \
          --build-version ${{ env.BUILD_VERSION }} \
          --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-linux
          path: src/build/linux
          if-no-files-found: error

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Python dependencies
        working-directory: ./src
        run: |
          python -m pip install --upgrade pip
          pip install flet==${{ env.FLET_VERSION }}
          pip install torch --index-url https://download.pytorch.org/whl/cpu --no-cache-dir
          pip install -r requirements.txt --no-cache-dir
          python -c "import torch; print(f'PyTorch version: {torch.__version__}, CUDA: {torch.cuda.is_available()}')"
          pip cache purge

      - name: Build macOS Application
        working-directory: ./src
        run: |
          rm -rf build/
          flet build macos \
          --project-name "${{ env.APP_NAME }}" \
          --description "Bob The Lawyer Application" \
          --build-number ${{ env.BUILD_NUMBER }} \
          --build-version ${{ env.BUILD_VERSION }} \
          --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-macos
          path: src/build/macos
          if-no-files-found: error

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Python dependencies
        working-directory: ./src
        run: |
          python -m pip install --upgrade pip
          pip install flet==${{ env.FLET_VERSION }}
          pip install torch --index-url https://download.pytorch.org/whl/cpu --no-cache-dir
          pip install -r requirements.txt --no-cache-dir
          python -c "import torch; print('PyTorch version: ' + torch.__version__ + ', CUDA: ' + str(torch.cuda.is_available()))"
          pip cache purge

      - name: Build Windows Application
        working-directory: ./src
        run: |
          rm -rf build/
          flet build windows \
          --project-name "${{ env.APP_NAME }}" \
          --description "Bob The Lawyer Application" \
          --build-number ${{ env.BUILD_NUMBER }} \
          --build-version ${{ env.BUILD_VERSION }} \
          --no-rich-output \
          --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-windows
          path: src/build/windows
          if-no-files-found: error