name: Build Bob Application (Linux)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  APP_NAME: "Bob"
  BUILD_NUMBER: 1
  BUILD_VERSION: "1.0.0"
  PYTHON_VERSION: "3.10.15"
  FLET_CLI_VERSION: "0.27.6"
  FLUTTER_VERSION: "3.27.4"
  PYTHONUTF8: 1

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends ninja-build libgtk-3-dev patchelf
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*

    - name: Create requirements with CPU-only PyTorch
      working-directory: ./src
      run: |
        echo "flet==$FLET_CLI_VERSION" > requirements.txt
        echo "accelerate" >> requirements.txt
        # Explicitly install CPU-only version of PyTorch
        echo "torch==2.7.1+cpu --index-url https://download.pytorch.org/whl/cpu" >> requirements.txt
        echo "transformers" >> requirements.txt
        echo "pandas" >> requirements.txt
        echo "python-pptx" >> requirements.txt
        echo "python-docx" >> requirements.txt
        echo "pypdf2" >> requirements.txt

    - name: Install Python dependencies
      working-directory: ./src
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        # Verify we have CPU-only PyTorch
        python -c "import torch; print(f'PyTorch version: {torch.__version__}'); print(f'CUDA available: {torch.cuda.is_available()}')"
        pip cache purge

    - name: Configure build
      working-directory: ./src
      run: |
        echo "name: $APP_NAME" > pubspec.yaml
        echo "description: Bob The Lawyer Application" >> pubspec.yaml
        echo "version: $BUILD_VERSION+$BUILD_NUMBER" >> pubspec.yaml
        echo "environment:" >> pubspec.yaml
        echo "  sdk: '>=3.0.0 <4.0.0'" >> pubspec.yaml
        
        flutter config --enable-linux-desktop
        flutter pub get

    - name: Build application
      working-directory: ./src
      run: |
        rm -rf build/
        flet build linux \
          --build-number=$BUILD_NUMBER \
          --build-version=$BUILD_VERSION \
          --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}-linux
        path: src/build/linux
        if-no-files-found: error
