name: Build Flet Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.10.15
  FLET_CLI_VERSION: 0.27.6
  PYTHONUTF8: 1
  FLET_CLI_NO_RICH_OUTPUT: 1
  UV_NO_PROGRESS: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet-cli==$FLET_CLI_VERSION
        pip install accelerate transformers torch pandas python-pptx python-docx pypdf2

    - name: Flet Build Linux
      working-directory: ./src  # Specify source code location
      run: |
        flet build linux --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-build-artifact
        path: src/build/linux  # Updated path to reflect working directory
        if-no-files-found: error
        overwrite: false
