name: Build Bob Application (Cross-Platform)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  APP_NAME: "Bob"
  BUILD_NUMBER: 1
  BUILD_VERSION: "1.0.0"
  PYTHON_VERSION: "3.10.15"
  FLET_CLI_VERSION: "0.27.6"
  FLUTTER_VERSION: "3.27.4"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends ninja-build libgtk-3-dev patchelf
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*

    - name: Install Python packages (Cross-Platform Safe)
      working-directory: ./src
      run: |
        # Create clean virtual environment
        python -m venv venv
        source venv/bin/activate

        # Install packages with explicit platform compatibility
        pip install --no-cache-dir \
          --only-binary=:all: \
          --platform manylinux2014_x86_64 \
          --implementation cp \
          --python-version 310 \
          --target ./python-packages \
          torch==2.7.0 --index-url https://download.pytorch.org/whl/cpu \
          flet==$FLET_CLI_VERSION \
          accelerate==0.27.2 \
          transformers==4.38.2 \
          pandas==2.2.1 \
          python-pptx==0.6.23 \
          python-docx==1.1.0 \
          pypdf2==3.0.1

        # Create platform-neutral requirements.txt
        pip freeze | grep -v '@' > requirements.txt
        deactivate

    - name: Configure build
      working-directory: ./src
      run: |
        echo "name: $APP_NAME" > pubspec.yaml
        echo "version: $BUILD_VERSION+$BUILD_NUMBER" >> pubspec.yaml
        echo "environment:" >> pubspec.yaml
        echo "  sdk: '>=3.0.0 <4.0.0'" >> pubspec.yaml
        flutter config --enable-linux-desktop
        flutter pub get

    - name: Build application
      working-directory: ./src
      run: |
        rm -rf build/
        PYTHONPATH=$(pwd)/python-packages flet build linux \
          --build-number=$BUILD_NUMBER \
          --build-version=$BUILD_VERSION

    - name: Optimize build
      working-directory: ./src/build/linux
      run: |
        find . -type f -executable -exec strip -s {} \;
        rm -rf flutter/ephemeral flutter/assets/fonts/MaterialIcons-Regular.otf
        find . -name "*.debug" -delete

    - name: Package and upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}-linux
        path: src/build/linux
        if-no-files-found: error
