name: Build Bob Application (Linux)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  APP_NAME: "Bob"
  BUILD_NUMBER: 1
  BUILD_VERSION: "1.0.0"
  PYTHON_VERSION: "3.10.15"
  FLET_CLI_VERSION: "0.27.6"
  FLUTTER_VERSION: "3.27.4"
  PYTHONUTF8: 1

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends ninja-build libgtk-3-dev patchelf
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*

    - name: Install Python dependencies
      working-directory: ./src
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.7.0 --index-url https://download.pytorch.org/whl/cpu
        pip install \
          flet==$FLET_CLI_VERSION \
          accelerate==1.6.0 \
          transformers==4.38.2 \
          pandas==2.2.1 \
          python-pptx==1.0.2 \
          python-docx==1.1.2 \
          pypdf2==3.0.1 \
          --no-cache-dir

    - name: Configure build
      working-directory: ./src
      run: |
        echo "name: $APP_NAME" > pubspec.yaml
        echo "version: $BUILD_VERSION+$BUILD_NUMBER" >> pubspec.yaml
        echo "environment:" >> pubspec.yaml
        echo "  sdk: '>=3.0.0 <4.0.0'" >> pubspec.yaml
        flutter config --enable-linux-desktop
        flutter pub get

    - name: Build application
      working-directory: ./src
      run: |
        rm -rf build/
        flet build linux \
          --build-number=$BUILD_NUMBER \
          --build-version=$BUILD_VERSION

    - name: Optimize build size
      working-directory: ./src/build/linux
      run: |
        # Remove debug symbols and unnecessary files
        find . -type f -executable -exec strip -s {} \;
        rm -rf flutter/ephemeral
        rm -rf flutter/assets/fonts/MaterialIcons-Regular.otf
        find . -name "*.debug" -delete

    - name: Package build
      working-directory: ./src/build
      run: |
        mv linux ${APP_NAME}_linux
        tar -czvf ${APP_NAME}_linux.tar.gz ${APP_NAME}_linux
        du -sh ${APP_NAME}_linux.tar.gz

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}-linux
        path: src/build/${{ env.APP_NAME }}_linux.tar.gz
        if-no-files-found: error
