name: Build Bob Application (Linux)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  APP_NAME: "Bob"
  BUILD_NUMBER: 1
  BUILD_VERSION: "1.0.0"
  PYTHON_VERSION: "3.11.10"
  FLET_VERSION: "0.27.6"
  FLUTTER_VERSION: "3.27.4"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends ninja-build libgtk-3-dev patchelf
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        
    - name: Setup Python environment
      run: |
        # Create completely isolated environment
        python -m venv --clear flet_env
        source flet_env/bin/activate
        
        # Use older pip version that's more stable
        python -m pip install pip==23.3.1
        
        # Set environment variables to avoid conda packages
        export PYTHONNOUSERSITE=1
        export PIP_NO_CACHE_DIR=1
        export PIP_INDEX_URL=https://pypi.org/simple/
        
        # Install core packages first
        pip install setuptools wheel
        
    - name: Install Python dependencies
      run: |
        source flet_env/bin/activate
        export PYTHONNOUSERSITE=1
        export PIP_NO_CACHE_DIR=1
        export PIP_INDEX_URL=https://pypi.org/simple/
        
        # Try alternative approach: install Flet without problematic dependencies
        pip install --no-deps flet==${{ env.FLET_VERSION }}
        
        # Install Flet's dependencies manually, skipping problematic ones
        pip install \
          flet-core \
          flet-runtime \
          watchdog \
          websockets \
          httpx \
          packaging \
          pandas \
          python-pptx \
          python-docx \
          pypdf2
          
    - name: Configure build
      working-directory: ./src
      run: |
        echo "name: ${{ env.APP_NAME }}" > pubspec.yaml
        echo "version: ${{ env.BUILD_VERSION }}+${{ env.BUILD_NUMBER }}" >> pubspec.yaml
        echo "environment:" >> pubspec.yaml
        echo "  sdk: '>=3.0.0 <4.0.0'" >> pubspec.yaml
        flutter config --enable-linux-desktop
        flutter pub get
        
    - name: Verify Flet installation
      run: |
        source flet_env/bin/activate
        flet --version
        which flet
        
    - name: Build application
      working-directory: ./src
      run: |
        source ../flet_env/bin/activate
        rm -rf build/
        flet build linux \
          --build-number=${{ env.BUILD_NUMBER }} \
          --build-version=${{ env.BUILD_VERSION }}
          
    - name: Optimize build
      working-directory: ./src/build/linux
      run: |
        find . -type f -executable -exec strip -s {} \; 2>/dev/null || true
        rm -rf flutter/ephemeral flutter/assets/fonts/MaterialIcons-Regular.otf 2>/dev/null || true
        find . -name "*.debug" -delete 2>/dev/null || true
        
    - name: Package and upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}-linux
        path: src/build/linux
        if-no-files-found: error
